name: Deploy Frontend

on:
  workflow_dispatch:

#   release:
#     types:
#       - released
#       - prereleased
#     tags:
#       - "frontend_*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Create .env.production file
        run: |
          echo "VITE_GOOGLE_OAUTH_CLIENT_ID='${{ vars.GOOGLE_OAUTH_CLIENT_ID }}'" > .env.production
          echo "VITE_API_URL='${{ vars.API_URL }}'" >> .env.production

      - name: Build
        run: yarn build
        working-directory: apps/frontend

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: trinks-express-build
          path: apps/frontenddist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: trinks-express-build
          path: dist

      - name: Sync files to S3 bucket
        run: |
          aws s3 cp dist s3://${{ vars.FRONTEND_BUCKET }} --recursive --cache-control max-age=31536000
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUITION }} --paths "/*"
