name: Deploy API

on:
  workflow_dispatch:
#   release:
#     types:
#       - released
#       - prereleased
#     tags:
#       - "api_*"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Create .env.prod file
        run: |
          echo "DOMAIN='${{ vars.DOMAIN }}'" > services/api/.env.prod
          echo "SUBDOMAIN='${{ vars.SUBDOMAIN }}'" >> services/api/.env.prod
          echo "FRONTEND_URL='${{ vars.FRONTEND_URL }}'" >> services/api/.env.prod
          echo "MONGO_URI='${{ secrets.MONGO_URI }}'" >> services/api/.env.prod
          echo "GOOGLE_OAUTH_CLIENT_ID='${{ vars.GOOGLE_OAUTH_CLIENT_ID }}'" >> services/api/.env.prod
          echo "GOOGLE_OAUTH_CLIENT_SECRET='${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}'" >> services/api/.env.prod
          echo "GOOGLE_OAUTH_REDIRECT='${{ vars.GOOGLE_OAUTH_REDIRECT }}'" >> services/api/.env.prod

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd services/api && serverless deploy --stage prod"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
